### ISSUE TITLE
Regression: cryptography library support for x509 certificate

### ISSUE THREAD

**Issue by danielfaust** [mpdavis/python-jose#106]
Some dependency related issue came up in my Docker container which makes use of `python-jose`. It appears that something stopped installing `pycrypto`. I'm not sure if it used to get installed alongside `python-jose` due to the contents of the `requirements.txt` file, which contained `pycrypto` until this commit: https://github.com/mpdavis/python-jose/commit/b08a58fabf1e6080f3729167d672729751fcb702#diff-b4ef698db8ca845e5845c4618278f29a 

Whichever the reason is why `pycrypto` isn't requested anymore in my dependency tree, for some reason `python-jose` is now using the `cryptography` backend (https://github.com/mpdavis/python-jose/blob/master/jose/backends/cryptography_backend.py), I think it is because I'm installing the `service_identity` module which pulls in `pyopenssl` and that in turn pulls in `cryptography`.

I just noticed that the `cryptography` module is recommended as the default one: https://github.com/mpdavis/python-jose#custom-backends

Here's the problem:

The `pycrypto` backend is able to load keys from x509 certificates, which are used by Google's GitKit and also by Firebase. The current code for the `cryptography` backend is not able to do this and triggers an exception due to a deserialization error `JWKError: Could not deserialize key data` both for GitKit and for Firebase.

Initial x509 certificates support got added due to this issue https://github.com/mpdavis/python-jose/issues/27#issuecomment-242092991

The modification in the snippet below at `key.startswith('-----BEGIN CERTIFICATE-----'):` fixes the issue, but I am not able to further deal with this issue due to time constraints, currently I'm solving this issue "manually" issuing a `pip install pycrypto` in the Dockerfile (other parts of my code depend on `pycrypto`, so I need to install it anyway).

Please read the blue note at https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/#pem
which leads to this document
https://cryptography.io/en/latest/x509/reference/#cryptography.x509.load_pem_x509_certificate

Please apologize for just stating the problem here. The modified code is the following (in this file https://github.com/mpdavis/python-jose/blob/master/jose/backends/cryptography_backend.py#L196):

```
class CryptographyRSAKey(Key):
    SHA256 = hashes.SHA256
    SHA384 = hashes.SHA384
    SHA512 = hashes.SHA512

    def __init__(self, key, algorithm, cryptography_backend=default_backend):
        
        if algorithm not in ALGORITHMS.RSA:
            raise JWKError('hash_alg: %s is not a valid hash algorithm' % algorithm)

        self.hash_alg = {
            ALGORITHMS.RS256: self.SHA256,
            ALGORITHMS.RS384: self.SHA384,
            ALGORITHMS.RS512: self.SHA512
        }.get(algorithm)
        self._algorithm = algorithm

        self.cryptography_backend = cryptography_backend

        # if it conforms to RSAPublicKey interface
        if hasattr(key, 'public_bytes') and hasattr(key, 'public_numbers'):
            self.prepared_key = key
            return

        if isinstance(key, dict):
            self.prepared_key = self._process_jwk(key)
            return

        if isinstance(key, six.string_types):
            key = key.encode('utf-8')

        if isinstance(key, six.binary_type):
            if key.startswith('-----BEGIN CERTIFICATE-----'): # <####### FROM HERE
              try:
                  key = x509.load_pem_x509_certificate(key, self.cryptography_backend())
                  self.prepared_key = key.public_key()
              except Exception as e:
                  raise JWKError(e)
            else: # <####### TO HERE
              try:
                  try:
                      key = load_pem_public_key(key, self.cryptography_backend())
                  except ValueError:
                      key = load_pem_private_key(key, password=None, backend=self.cryptography_backend())
                  self.prepared_key = key
              except Exception as e:
                  raise JWKError(e)
            return

        raise JWKError('Unable to parse an RSA_JWK from key: %s' % key)
```
This is the way it got fixed for pycrypto back then: https://github.com/mpdavis/python-jose/blob/e70b62583b272b2c040df613b4e264e5d08e176a/jose/backends/pycrypto_backend.py#L64

**Comment by mpdavis** [comment]
Thanks for the heads-up on cryptography not supporting x509 certificates. We have a hole in our tests around that. I have updated that here: https://github.com/mpdavis/python-jose/pull/107

You are correct, we did switch the default backend from `pycrypto` to `cryptography`. This was done with a breaking change in version `3.0.0`

If the new version doesn't work for you for some reason, you can update any references to `python-jose` with `python-jose[pycrypto]` wherever you install it (pip, requirements.txt). However, using `cryptography` is highly recommended.

**Comment by mpdavis** [comment]
Fixed in https://github.com/mpdavis/python-jose/releases/tag/3.0.1

**Comment by danielfaust** [comment]
> However, using cryptography is highly recommended.

I just want to point out that `pycryptodome` appears to be the new default. There might be a good reason for this, but it somehow contradicts the above statement.

Thank you for the effort you put into this library.

**Comment by zejn** [comment]
@danielfaust pycryptodome was default for a short while, yes. Currently, the default is pure-python, which can be very slow, so it's recommended to install one of the faster backends.

You can choose this backend by running `pip install python-jose[cryptography]` or `pip install python-jose[pycryptodome]`.

Best is probably cryptography.
