### ISSUE TITLE
install_requires 'future' even in a python3 environment

### ISSUE THREAD

**Issue by lestephane** [mpdavis/python-jose#112]
(arrived here from https://github.com/UnitedIncome/serverless-python-requirements/issues/285#issuecomment-441324344)

I'm experiencing lambda python packages that are much larger than they should be in a Python3 environment because Jose depends on **future**, even though future is only needed in a python 2.6 environment.
 
https://github.com/mpdavis/python-jose/blob/7bc6b980c220037cdb356606515542699bf49421/setup.py#L68

Is this a limitation inherent to python? How to avoid pulling in future?

**Comment by zejn** [comment]
Fixed in #134.
