### ISSUE TITLE
six requirement

### ISSUE THREAD

**Issue by scipioni** [mpdavis/python-jose#12]
python-jose depends from six < 1.10.0 as specified in setup.py

        'six >=1.9.0, <1.10.0',

This behaviour breaks other packages like html5lib and others and it is difficult keep virtualenv clean
after an upgrade of packages

**Comment by scipioni** [comment]
Meanwhile I use https://pip.pypa.io/en/stable/user_guide/#requirements-files

**Comment by mpdavis** [comment]
The libraries I use are stable enough that I can probably relax that requirement.

**Comment by mpdavis** [comment]
I released version [0.5.6](https://github.com/mpdavis/python-jose/releases/tag/0.5.6).

Let me know if that works out for you.

**Comment by scipioni** [comment]
Yes, it works like a charms and six 1.10.0 give me no problems.

Thank you for all your assistance
