### ISSUE TITLE
Backend import priority

### ISSUE THREAD

**Issue by RazerM** [mpdavis/python-jose#123]
https://github.com/mpdavis/python-jose/blob/cc710e04a1c7096c3d37efffaf2877f88beebda5/jose/backends/__init__.py#L2-L8

`pycrypto` and `cryptography` should swap places here for the case where both are installed.

**Comment by RazerM** [comment]
Oops I only searched issues, but there's already a PR #122

**Comment by zejn** [comment]
Merged #122
