### ISSUE TITLE
0.6.0 release broke Python 2.7 compatibility

### ISSUE THREAD

**Issue by dokai** [mpdavis/python-jose#14]
It seems the latest 0.6.0 release broke compatibility with Python 2.7 due to the `from builtins import int` in `jwk.py`. Is there a particular use case that import supports? It seems other parts (e.g. `jwt.py`) are still using the default `int` binding from the global namespace.

I'd like to propose the removal of that import or wrapping it with a try/except if it is indeed needed for Python 3.

**Comment by mpdavis** [comment]
Whoops, that is my bad.  I forgot to include the future dependency in the distribution. 

Despite it's name, that `int` import is necessary for supporting longs in both python2 and python3.  

I'll have a fix is a sec.

**Comment by mpdavis** [comment]
https://github.com/mpdavis/python-jose/releases/tag/0.6.1 Fixes this on my machine.  Let me know if you run into any issues.

**Comment by mpdavis** [comment]
I have also removed `0.6.0` from pypi to avoid others having the same issue.

**Comment by dokai** [comment]
Great! Thanks for the quick fix and release.
