### ISSUE TITLE
Python Social Auth fails for jwk.construct(key) when missing 'alg'

### ISSUE THREAD

**Issue by cgthayer** [mpdavis/python-jose#144]
Hi, I'm working on an integration with onelogin for SSO. I'm using python-social-auth openid_connect which is throwing this exception:

```
jose.exceptions.JWKError: Unable to find a algorithm for key: {'kty': 'EC', 'kid': '3B2VqQDG7Zere66666666', 'use': 'sig', 'x': 'Bzs6VlmYJUNcON18AZjAtDAsksksksksksksksksksksk', 'y': 'sujDlptuEPFujgcIPa-x-AN2Grmr-Y90-CdCdCDCdCDcD', 'crv': 'P-256'}
```
It appears that the token I get back doesn't include 'alg'.

I believe that jose.jwk should attempt to use RS256 in this case if 'alg' is missing from the key, based on https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation in Section "3.1.3.7.  ID Token Validation" see line 7 "The alg value SHOULD be the default of RS256 or the algorithm sent by the Client in the id_token_signed_response_alg parameter during Registration."

The change would be jwk.py:53

```
    algorithm = key_data.get('alg', ALGORITHMS.RS256)
```

Thanks

**Comment by eduzen** [comment]
I have the same problem, but if you do your fix it will complain later.

```
    key_data['alg'] = ALGORITHMS.RS256
    algorithm = key_data.get('alg', None)
```

It worked for me like this.

**Comment by blag** [comment]
Closing - this project is the wrong place to fix this, it should be fixed in [python-social-auth/social-core](https://github.com/python-social-auth/social-core). Please move any further discussion to #171.

**Comment by dimaqq** [comment]
Interesting, the `kty: "EC"` means it's an elliptic curves key, `crv: "P-256"` means it's `ES256`.
It's certainly not `RS256`.

Having implemented an OIDC server, my key discovery endpoint also doesn't include `alg` in the published keys...
I wonder if it's a `pyjwt` bug, or I misunderstood the spec 🤔
