### ISSUE TITLE
Allow jwt.decode audience to be an iterable

### ISSUE THREAD

**Issue by bgrant** [mpdavis/python-jose#148]
Currently, `audience` in `jwt.decode` will only accept a `str`:

```
        audience (str): The intended audience of the token.  If the "aud" claim is
            included in the claim set, then the audience must be included and must equal
            the provided claim.
```

It would be useful if an iterable could be passed in for `audience`, with the meaning that the "aud" claim must be included and match *one of* the values in `audience`.

**Comment by blag** [comment]
Here's the [section in the JWT spec](https://tools.ietf.org/html/rfc7519#section-4.1.3) on the `aud` claim:

>   The "aud" (audience) claim identifies the recipients that the JWT is
>   intended for.  Each principal intended to process the JWT MUST
>   identify itself with a value in the audience claim.

My understanding of that spec is that a principal can only identify with a single audience, but a JWT may specify one or more intended audiences ("recipients") in its `aud` claim, as a list of "StringOrURI" values, or just a single "StringOrURI" value.

If I'm correct, then `jwt.decode` accepting only a single string in its `audience` keyword parameter is actually correct, but that it should accept either a single string or a list of strings in the `aud` claim of JWTs. The `jwt.decode` currently only supports a single string in JWT `aud` claims and does _not_ support JWTs that specify multiple intended audiences with a list of strings. PR #170 fixes this.

Here's the rest of that section:

>   ... If the principal
>   processing the claim does not identify itself with a value in the
>   "aud" claim when this claim is present, then the JWT MUST be
>   rejected.  In the general case, the "aud" value is an array of case-
>   sensitive strings, each containing a StringOrURI value.  In the
>   special case when the JWT has one audience, the "aud" value MAY be a
>   single case-sensitive string containing a StringOrURI value.  The
>   interpretation of audience values is generally application specific.
>   Use of this claim is OPTIONAL.

@zejn @mpdavis You both may have a better understanding than I do on this. Can I get your opinion/s?

**Comment by blag** [comment]
As far as I can tell, the proper way to handle this (if you can control the JWT claims) is to omit the `aud` claim entirely from the JWT. Since the `aud` claim is `OPTIONAL` according to the spec, the principal should not reject the JWT due to a missing `aud` claim.

However, if you really would like the functionality and you cannot control the JWT claims, here is a Python function that implements it:

```python
from jose import jwt
from jose.exceptions import JWTClaimsError

key = 'secret'
claims = {
    'aud': ['one audience', 'another audience'],
}
token = jwt.encode(claims, key)


def check_multiple_audiences(token, key, audiences):
    for audience in audiences:
        try:
            jwt.decode(token, key, audience=audience)
        except JWTClaimsError:
            pass
        else:
            break
    else:
        raise JWTClaimsError("None of the provided audiences matched the audience/s in the JWT claims")


check_multiple_audiences(token, key, ['one audience', 'another audience'])
check_multiple_audiences(token, key, ['audience one', 'audience two'])
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "<stdin>", line 10, in check_multiple_audiences
# jose.exceptions.JWTClaimsError: None of the provided audiences matched the audience/s in the JWT claims
```

Since this project currently implements the RFC as it is written, and you now have a workaround for what you're trying to do, I'm closing this issue.

**Comment by rajanjha786** [comment]
This feature will help to do an evolving change instead of breaking change.
Now I have to change the audience of service but I can not change the audience directly because it will break all my clients instead I want to support both the audience for a time being and give time to my consumer to adapt.
Thanks, @blag even I was thinking to implement something like you suggested as a workaround.

**Comment by toniton** [comment]
Ref: https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3
_Each principal intended to process the JWT MUST identify itself with a value in the audience claim.  If the principal processing the claim does not identify itself with a value in the "aud" claim when this claim is present, then the JWT MUST be rejected._

I really don't understand the use-case where you need to decode multiple arrays.

Here is a short explanation of my understanding in steps:
1. You have a principal, let's call this service a Guard A. 
2. The job of the guard is to verify the claim.
3. Your claim can have multiple audience.
4. Audiences are Client A, Client B.
5. Client A gets the claim and passes it to Client B.
6. Client B needs to talk to Service M
7. Service M is a guarded service protected by Guard A.
8. Client B sends JWT to Guard A.
9. Guard A checks if Client B is an audience in the JWT.

Simplified illustration:
![jwt-audience-claim-explained](https://github.com/mpdavis/python-jose/assets/5252828/302de5e6-1eb5-4796-bf31-7d4a1ac01162)

While JWT can be passed around and reused by other clients, the claim can only be presented by one client/service.
JWT verification is therefore a one-to-one interaction between services, which would mean that you need only one audience in `jwt.decode`.
