### ISSUE TITLE
A 3.0.2 release to release the fix to #75

### ISSUE THREAD

**Issue by techdragon** [mpdavis/python-jose#155]
While I'm aware of a desire to finish a larger update to this library ( #145 ), I'd like to voice my need for a smaller release _sooner_... Since this library is often used as a dependency, in particular by libraries such as `python_social_auth`, we really need a release on pypi that includes the changes that fixed #75 which fixes things so that correct standards compliant behaviour no longer causes errors when using things built on this library. ( that is, a release that includes PR #76 ) 

It's problematic that we can't write downstream libraries, specifying that they require a version of this library that is correctly standards compliant, so a patch release `x.x.+1` that added only this fix would be really handy.

**Comment by kkozmic** [comment]
It would be lovely to see a release with the #124 fix soon as well.

**Comment by blag** [comment]
Resolved by #157. I'm working on this.

**Comment by blag** [comment]
Version [3.1.0](https://pypi.org/project/python-jose/3.1.0/) is now released on PyPI and GitHub, which contains #76 and #124.
