### ISSUE TITLE
Python 3.8 Deprecation Warning

### ISSUE THREAD

**Issue by Syntactical01** [mpdavis/python-jose#158]
I am getting a Deprecation warning from pylint with the latest version of `python-jose==3.0.1`:
```
env/lib/python3.7/site-packages/jose/jws.py:6
  /Users/me/Repos/webapp/env/lib/python3.7/site-packages/jose/jws.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Mapping, Iterable
```
I am currently using Python 3.7, so I can ignore the warning, but I am hoping to upgrade to Python 3.8 in the future.

**Comment by kkozmic** [comment]
This looks like it might be a duplicate of #124

**Comment by Syntactical01** [comment]
Is it just not pushed in an official release yet? My version matches the latest release (at least it appears to be the latest release according to pip).

**Comment by kkozmic** [comment]
No, it isn't yet

**Comment by Syntactical01** [comment]
Closing, as this appears to have a duplicate, though hoping this is merged *soon*.
