### ISSUE TITLE
Support for JWT custom claims

### ISSUE THREAD

**Issue by JohnPaton** [mpdavis/python-jose#175]
It would be nice for `jwt.decode` to support an additional `custom_claims` dict for verification. 

Examples:

```pycon
>>> from jose import jwt

>>> token = jwt.encode({"custom": "test"}, key="secret")

>>> jwt.decode(token, key="secret")
{'custom': 'test'}

>>> jwt.decode(token, key="secret", custom_claims={"custom": "test"})
{'custom': 'test'}

>>> jwt.decode(token, key="secret", custom_claims={"custom": "something else"})
Traceback (most recent call last):
  [ ... ]
jose.exceptions.JWTClaimsError: Invalid custom claims

>>> jwt.decode(token, key="secret", custom_claims={"other key": "value"})
Traceback (most recent call last):
  [ ... ]
jose.exceptions.JWTClaimsError: Invalid custom claims
```

I would be happy to work on a PR for this if there is interest in the feature.

**Comment by mpdavis** [comment]
Hey @JohnPaton,

I don't believe python-jose is the right spot for this functionality as it isn't part of any of the JOSE RFCs. This library wouldn't have any concept of what makes those custom claims valid or invalid. 

There isn't anything stopping you from doing custom claim checking after the decode step to verify any custom requirements on the internal claims.

Thanks.

**Comment by JohnPaton** [comment]
Fair enough, thanks for the quick reply.
