### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by nantha42** [mpdavis/python-jose#177]
I am using python3 but the print statement is without brackets!
`
Traceback (most recent call last):
  File "/Users/nantha/Projc/my_projects/intern/extract_log.py", line 2, in <module>
    import jose
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jose.py", line 546
    print decrypt(deserialize_compact(jwt), {'k':key},
                ^
SyntaxError: invalid syntax
`

**Comment by stanislaw** [comment]
I got this error when I tried installing jose using PyCharm which installed a different package: `jose` instead of 

```bash
$ pip install python-jose[cryptography]
```

as required in the documentation.

Solution: don't rely on PyCharm, install from command line.

**Comment by ricciarellif** [comment]
> I got this error when I tried installing jose using PyCharm which installed a different package: `jose` instead of
> 
> ```shell
> $ pip install python-jose[cryptography]
> ```
> 
> as required in the documentation.
> 
> Solution: don't rely on PyCharm, install from command line.

The proposed solution worked for me: thanks!
