### ISSUE TITLE
API Docs not rendering on readthedocs.io

### ISSUE THREAD

**Issue by bjmc** [mpdavis/python-jose#190]
This is rendering as a mostly-blank page for me https://python-jose.readthedocs.io/en/latest/jwt/api.html

![image](https://user-images.githubusercontent.com/328557/94826471-3f641700-03ff-11eb-9c18-36a41f16133d.png)

**Comment by andrew-chang-dewitt** [comment]
Looks like this needs re-opened:

![image](https://user-images.githubusercontent.com/11323923/149601832-e0ad66cc-8a24-4757-98f5-2350bb203be4.png)
