### ISSUE TITLE
decode token without key argument

### ISSUE THREAD

**Issue by david-shiko** [mpdavis/python-jose#206]
Hello! I have a token that every online jwt decoder (like https://jwt.io/) can to decode, but with `jose` I can't do it because I need a key as required positional argument... can I somehow omit it, or what I should to do?

```
from jose import jwt


token = eyJhbGciOiJSUzI1NiIsImtpZCI6ImVlYTFiMWY0MjgwN2E4Y2MxMzZhMDNhM2MxNmQyOWRiODI5NmRhZjAiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiIxNjcwMzExMDQ1NjYtYmZpMmgyODdzMWYxdTFzaWFicGI1ZWo4OHExa25nMnMuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiIxNjcwMzExMDQ1NjYtYmZpMmgyODdzMWYxdTFzaWFicGI1ZWo4OHExa25nMnMuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMDEyODA4NDEwNzU2MjUwMzQwMjAiLCJlbWFpbCI6ImRzYjMyMW1wQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhdF9oYXNoIjoiWmpVY1Eyd3JkLUdzY3F2Y2dqci1BQSIsIm5vbmNlIjoiUFp2SGhsX2tUTGR1Sktmem80LW9qdyIsImlhdCI6MTYxMTY5MjA2NywiZXhwIjoxNjExNjk1NjY3fQ.kNFbqjtJO2HKsSX-jt967MLi2xjeRH4W9JsA4yPQDQEgrHqa3BX6PVFJCBjq-Fn7vmlTT1lUcElVPwtvcBUV8Z4I7dCuWKcTxTt6R8501f1I2X0tQeEu_zfg-ianzOlQkg3KvLT_D-oaIfNkoU7jAt4Mywe6xHiDKszlA6KE8T6PLV_VeiCJGvciLbPW7DhKiuL-kfTjhHoZ6_XHeruR6rb_psZNvH5t-D3Yjc27EwH0_Wumcl1GjN20eF2xO-UDhO4BMRHGIM5876QUYB58dxblLG1flEaeXi9z4R-XnrLPYpAYZDYQDcPMni9fUm9d8pNZDeTGh6WyGkTqkXuHvg

jwt.decode(token=token, key=???, algorithms='RS256')
```

**Comment by chrisjbremner** [comment]
Something like this would work:
```python
jwt.decode(token, key=None, options={"verify_signature":False})
```
Note that you will still get a `jose.exceptions.ExpiredSignatureError` if the signature is expired, which differs from jwt.io, which gives you the decoded token anyways.

**Comment by mpdavis** [comment]
If you don't have the key to verify the token, then you absolutely shouldn't be trusting the token in any way. 

If you need to read the claims without actually verifying the token, you can use the [jws API](https://github.com/mpdavis/python-jose/blob/master/jose/jws.py#L94-L125) to do so, or just manually base64 decode the claims section of the JWT.

**Comment by alexjolig** [comment]
If you just need the claims, you can use `jwt.get_unverified_claims()`
