### ISSUE TITLE
Dependency on google app engine. 

### ISSUE THREAD

**Issue by HW-Siew** [mpdavis/python-jose#21]
Hi, I tried to use this on google app engine. A few of dependency are required, six.py and builtins. Am i going to add the required module manually or i missed out configuration on google app engine? Thanks for the advice.

**Comment by mpdavis** [comment]
You will need to add them.

This [stackoverflow post](http://stackoverflow.com/a/14851686/1040949) explains how to do that.

**Comment by mpdavis** [comment]
You can also check out Google's [documentation](https://cloud.google.com/appengine/docs/python/tools/using-libraries-python-27#vendoring) on including third party libraries.

**Comment by HW-Siew** [comment]
ok, Thanks.

**Comment by makjoobali** [comment]
I added all the libraries just like @mpdavis suggested however I still get the following error when I start the server. @HW-Siew  did you resolve this ?

```
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/yaml_listener.py", line 178, in _HandleEvents
    raise yaml_errors.EventError(e, event_object)
google.appengine.api.yaml_errors.EventError: the library "jose" is not supported
  in "app_dev.yaml", line 25, column 1

```
