### ISSUE TITLE
0.6.x versions broke google appengine compatibility (subprocess dependency)

### ISSUE THREAD

**Issue by fabito** [mpdavis/python-jose#23]
I'm using python-jose on GAE and had to fallback to 0.5.6.
0.6.x versions are no working.
Seems like its related to the "builtins" dependency (which depends on unavailable subprocess module [1]) introduced in this commit:

https://github.com/mpdavis/python-jose/commit/babfe193988fb187217f9afd0fd6f46dbdbcf108

[1] https://cloud.google.com/appengine/kb/#libraries

**Comment by mpdavis** [comment]
Well that isn't going to work.

I'll get a fix out shortly.

**Comment by mpdavis** [comment]
@fabito I submitted a fix and tagged version [0.7.0](https://github.com/mpdavis/python-jose/releases/tag/0.7.0) which should fix the issue. 

Let me know if you continue to have issues.

**Comment by fabito** [comment]
@mpdavis , I just tried 0.7.0 and seems to be working fine - at least `jwt.decode` which is the only method I'm currently using.

thanks!

**Comment by mpdavis** [comment]
Thanks for checking and getting back to me.
