### ISSUE TITLE
Please switch to pycryptodomex

### ISSUE THREAD

**Issue by jdunck** [mpdavis/python-jose#26]
Guidance from pycryptodome is to use "pycryptodomex" unless you know you're installing to a virtualenv:

http://pycryptodome.readthedocs.io/en/latest/src/introduction.html

I think since this is a library, it would be better to require pycryptodomex and code to that.  I'd be happy to do a PR if you agree.

(I noticed this because we have a couple libraries with transitive deps to jose and to pyjwkest (both).  But they depend on both pycryptodome and pycryptodomex, which is a pain.)

**Comment by mpdavis** [comment]
I admittedly don't have much experience with PyPy, but this seems like the correct course.  

I would welcome a PR.

**Comment by jdunck** [comment]
Ah, I missed in the setup.py that this is only used for PyPy.  Is there a reason you prefer PyCrypto over Cryptography?

**Comment by mpdavis** [comment]
Unfortunately, Cryptography is not supported on Google's AppEngine, which I wrote this library to be fully compatible with.

**Comment by jdunck** [comment]
That's a good reason, alas.  Closing this issue. :P
