### ISSUE TITLE
Minor bump version is backward compatible.

### ISSUE THREAD

**Issue by mariajgrimaldi** [mpdavis/python-jose#266]
According to https://semver.org/, minor bumps are backward compatible. But 3.3.0 version drops support for python 3.5, why is a minor increase?

**Comment by blag** [comment]
Python 3.5 has reached end of life status, so dropping support for it should not be a breaking change for users - they should have already upgraded off of it.

SemVer (IMO) refers to code compatibility rather than Python runtime compatibility.

**Comment by mariajgrimaldi** [comment]
Excellent, thank you for the answer @blag.
