### ISSUE TITLE
Is there currently a way to add custom headers when creating JWE?

### ISSUE THREAD

**Issue by rudi-matricata** [mpdavis/python-jose#271]
For example I want to add 'iat' header. I couldn't see this to be supported. Is it not?

**Comment by rudi-matricata** [comment]
@blag Hello, I saw that you contributed for JWE impl. Are you familiar with the question?

Thanks and Regards,
Radoslav

**Comment by blag** [comment]
If you are specifically asking about the `iat` header, that's a [reserved header](https://python-jose.readthedocs.io/en/latest/jwt/index.html?highlight=iat) for JWTs, so it is already supported.

The JOSE standard(s), and this library, are non-opinionated as to what non-reserved headers are used.

But, in general, I would suggest a "try it and find out" approach to answering these questions, as that will let you know for sure.

**Comment by rudi-matricata** [comment]
What I'm talking about is specifically the JWE. I want to have the 'iat' header added for JWE. What we have now is:
def encrypt(plaintext, key, encryption=ALGORITHMS.A256GCM, algorithm=ALGORITHMS.DIR, zip=None, cty=None, kid=None)
You cannot specify anything else (e.g. 'iat' header) and of course I already tried it and it is not added by default (the 'iat' header I mean).

I see this as a not so small limitation.

Radoslav
