### ISSUE TITLE
[BUG] Wrong token parsing leading to unreadable JWTs

### ISSUE THREAD

**Issue by fmardero** [mpdavis/python-jose#277]
Hi,
the algorithm used to unpack (unsafely) the JWT in the [_load](https://github.com/mpdavis/python-jose/blob/be8e914a63e8940cd34ac0f5a066d114f10dad48/jose/jws.py#L172) function is not always able to correctly parse a valid JWT. 
For example, using [this token](https://jwt.io/#debugger-io?token=eyJhbGciOiJFUzI1NiIsImtpZCI6IkhRVlZOWTdKcHRSeUZ4NG5kREc2b0taM0lfU0VGd3MxWHFyNFUwMVdSMkUiLCJ0eXAiOiJKV1QifQ.eyJzdWIiOiJlOWE2MDZhZC01OTJlLTQ5YTItYmJhZC1kZmU0ZWFjMWMxOWYiLCJpc3MiOiI0NjQyYjVkYS1hMTc5LTRkNDUtYWJjZi03Yjc0YWRlNjliNDciLCJhdWQiOiJhY2JjNzJkZC01YjZiLTRkMmMtOTMzMi1mYTFhM2Q3ZTg5OGMiLCJuYmYiOjE2Mjk5MTc4MzcsImlhdCI6MTYyOTkxNzgzNywiZXhwIjoxNjM1MTAxODM3LCJqdGkiOiIxNThjNDI2Ny02NTdjLTQyZTItYmQ3Yi1iODRmNTIwMTE1NjAiLCJzY29wZSI6ImFjY291bnRpbmc6cmVhZCIsImNuZiI6eyJqa3QiOiJBTVhsd3pHRDdrVUJ1ZXkwSjZqRWo0MkJlR3poTVJMMEFlYzhsUUhPQWZnIn19.R5yu3bAkm7rB43R-KAvbqiYf_z_tuIN1fkxH3bgUnBnR6HbH6904P1IJQaQxpba5_3eLAPXVj9EVeUXWtiUQqw.eyJzdWIiOiI3ODU4MzlhMy1lYjk3LTQxYmYtYjUxZi1jYjk4NjA2MjUzODMiLCJpc3MiOiIyMGQ0MTA4Yi0zM2JkLTQ0NzktOTM2Ni01NjAzM2Q1YjFkNDEiLCJhdWQiOiJhY2JjNzJkZC01YjZiLTRkMmMtOTMzMi1mYTFhM2Q3ZTg5OGMiLCJuYmYiOjE2Mjk5MTY3MzgsImlhdCI6MTYyOTkxNjczOCwiZXhwIjoxNjM1MTAwNzM4LCJqdGkiOiJhZjA3OWYyNS1mYTIwLTRmNjMtOGM5Yy00N2E3YWJmYTNhMWMiLCJzY29wZSI6ImFjY291bnRpbmc6cmVhZCIsImNuZiI6eyJqa3QiOiJBTVhsd3pHRDdrVUJ1ZXkwSjZqRWo0MkJlR3poTVJMMEFlYzhsUUhPQWZnIn19.G411uBKwaucYWZJ1vm2MfnQw6DJwSKT0VJp8HinJANbzz6ofF3PikmWm7jPtXB3ysD0AcPcczs6v4dks5wRgSw) (encoded using the `jose.jwt.encode` function!) `jwt.io` parses it correctly while `jose.jwt.decode` does not.

Replacing as below the first rows of `_load` leads to the expected parsing:
```python
def _load(jwt):
    if isinstance(jwt, str):
        jwt = jwt.encode("utf-8")
    try:
        header_segment, claims_crypto_segments = jwt.split(b".", 1)
        claims_segment, crypto_segment = claims_crypto_segments.split(b".", 1)
        signing_input = b'.'.join([header_segment, claims_segment])
        header_data = base64url_decode(header_segment)
    except ValueError:
        raise JWEError("Not enough segments")
    except (TypeError, binascii.Error):
        raise JWSError("Invalid header padding")
...
```
Unfortunately I don't have the public key anymore so I'm not able to test the complete `jose.jwt.decode` function.

Hope it helps

**Comment by mpdavis** [comment]
The provided JWT isn't properly formatted. It includes a '.' character in the signature segment, which is tripping up the parsing logic. 

My assumption is that period was added inadvertently. Our library shouldn't ever add it. We encode that signature [here](https://github.com/mpdavis/python-jose/blob/master/jose/jws.py#L165) and that bas64 encoding will never include a period. 

I'm closing this for now, but feel free to re-open it if you can reproduce a period in the signature segment.
