### ISSUE TITLE
RFC document in tests/rfc/test_rfc7520.py

### ISSUE THREAD

**Issue by fladi** [mpdavis/python-jose#290]
[Debian prohibits the inclusion of RFC documents in it's sources](https://wiki.debian.org/NonFreeIETFDocuments), therefore in creating a Debian package out of python-jose requires me to exclude the whole test_rfc7520.py from the source tarball. As the document is only used in the form of comments, would it be reasonable to remove the actual RFC content from the file and just link to the original document?

**Comment by mpdavis** [comment]
I would be fine with excluding those. I included them originally to make writing the tests easier and to show why each case was being tested, but it isn't like they are changing a whole lot. If it makes it easier for packagers to remove those I would be on board with that.

**Comment by fladi** [comment]
Thanks for merging!

**Comment by fladi** [comment]
Just a heads-up, the [Debian package](https://tracker.debian.org/pkg/python-jose) has been uploaded to the archive, without the test_rfc7520.py for now, but the next release of python-jose should be able to enter the archive with an unmodified source tarball.
