### ISSUE TITLE
Unable to verify ADAL token signature

### ISSUE THREAD

**Issue by gmeans** [mpdavis/python-jose#32]
We're working w/ an app that is using adal.js to authenticate a user within a SPA, then afterwards we are looking to verify that token on the backend. 

We are trying to use the the `jwt.decode()` method but receive a 'Signature Verification Failed' error we can't figure out. Since Azure issues its public keys in RSA format we were trying to use the `jwk.RSAKey` object to create the public key for decoding.

The keys we are pointed to are posted here:

https://login.windows.net/common/discovery/keys

Here's the flow of our code.

```python
# token sent over from ADAL. We've pasted this string into http://jwt.calebb.net
# and everything appears to decode correctly.
token = "..."

# note there are multiple keys posted at the above URL, we select the right one by 
# looking at the kid attribute in the decoded token.
key_data=<dict from url posted above>

# Prepare the key using the RSA object
from jose.jwk import RSA
key = RSAKey(key_data, algorithm='RS256')

# Try to to use the exportKey() function to feed a PEM formatted
# key into jwt.decode()
jwt.decode(token, k.prepared_key.exportKey(), algorithms='RS256')
```

This results in a Signature verification failed error. We've also tried using jwk.construct() directly and calling verify but we have the same result.

Any ideas? Maybe we are using exportKey() incorrectly?

Thanks!

**Comment by mpdavis** [comment]
Do you have an example token I could test with?

An expired token would be fine.

**Comment by gmeans** [comment]
Sure is there a better way to get it to you? Feels weird posting a token here :)

**Comment by mpdavis** [comment]
You can email it to me.  

mike.philip.davis@gmail.com

**Comment by gmeans** [comment]
Thanks, just sent it.

**Comment by mpdavis** [comment]
It appears to me that the signature is legitimately incorrect and the token is correctly failing signature validation. 

I verified with the PyJWT library:

```python
>>> jwt.decode(t, k, algorithms=['RS256'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/michael/.envs/python-jose/lib/python2.7/site-packages/jwt/api_jwt.py", line 64, in decode
    options, **kwargs)
  File "/Users/michael/.envs/python-jose/lib/python2.7/site-packages/jwt/api_jws.py", line 116, in decode
    key, algorithms)
  File "/Users/michael/.envs/python-jose/lib/python2.7/site-packages/jwt/api_jws.py", line 186, in _verify_signature
    raise DecodeError('Signature verification failed')
jwt.exceptions.DecodeError: Signature verification failed
```

As well as the jwt.io website

![](https://dl.dropbox.com/s/pba80dahf5433pl/Screenshot%202016-08-10%2007.28.43.png?dl=0)

To verify, the public key I extracted from kid `MnC_VZcATfM5pOYiJHMba9goEKY` for testing is:

```
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvIqz+4+ER/vNWLON9yv8
hIYV737JQ6rCl6XfzOC628seYUPf0TaGk91CFxefhzh23V9Tkq+RtwN1Vs/z57hO
82kkzL+cQHZX3bMJD+GEGOKXCEXURN7VMyZWMAuzQoW9vFb1k3cR1RW/EW/P+C8b
b2dCGXhBYqPfHyimvz2WarXhntPSbM5XyS5v5yCw5T/Vuwqqsio3V8wooWGMpp61
y12NhN8bNVDQAkDPNu2DT9DXB1g0CeFINp/KAS/qQ2Kq6TSvRHJqxRR68RezYtje
9KAqwqx4jxlmVAQy0T3+T+IAbsk1wRtWDndhO6s1Os+dck5TzyZ/dNOhfXgelixL
UQIDAQAB
-----END PUBLIC KEY-----
```

**Comment by gmeans** [comment]
Thanks @mpdavis ! It helped knowing that at least our flow was right. I went through the process and generated new tokens and got everything to work.

I really appreciate the help!

**Comment by mpdavis** [comment]
@gmeans No problem.  I'm glad it ended up working.

**Comment by bj00rn** [comment]
for anyone else who ends up here, make sure to create a scope for your application in Azure AD as per https://medium.com/@abhinavsonkar/making-azure-ad-oidc-compliant-5734b70c43ff.

Without setting a scope token is issued with ms graph scope causing validation to fail

see explanation https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/609
