### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by hmehran** [mpdavis/python-jose#37]
I get this log output when trying to run python-jose on AWS
```
from jose import jwt
 ImportError: No module named jose
```

I have already confirmed that python-jose is already installed.
`Requirement already satisfied (use --upgrade to upgrade): python-jose==1.3.2 in /opt/python/run/venv/lib/python2.7/site-packages (from -r /opt/python/ondeck/app/requirements.txt (line 14))`

Any idea why this might be happening?

**Comment by mpdavis** [comment]
Are you sure that the same virtualenv is active when you are installing python-jose as when you are trying to import it?

To my knowledge, there shouldn't be any reason specific to AWS that is causing your issue.

**Comment by hmehran** [comment]
Yeah i believe you were right. I think i was just reading the output log incorrectly.
thanks
