### ISSUE TITLE
Odd issue with RFC5270 test

### ISSUE THREAD

**Issue by jrconlin** [mpdavis/python-jose#38]
Hi,
I'm currently working on a patch to allow python-jose to use pyelliptic. This is because we use the library in a fairly high-demand environment and would like to use a clib based EC handler. 

I have every test but one working. `tests.rfc.TestFourThreeThree.test_signature` is failing because OpenSSL flags that the point defined is not on curve. 

I have a gist that demonstrates the problem: https://gist.github.com/jrconlin/ad8c7f692235b0fd51ddbe20be09c272

(in that test, the "rfc" key is taken from the RFC text, "control" are a pair of points extracted from an openssl public key generated by:

`openssl  ecparam -name secp521r1 -genkey -noout | openssl ec -pubout`)

Oddly, if I take the RFC key values and reformat them as a raw key PEM, `openssl ecparam -check` says they're ok.

Hoping that I'm just doing something stupid, but if you have a moment, I'd greatly appreciate your input.

**Comment by mpdavis** [comment]
I would assume that it is an encoding, endianness, or some similar issue.  I don't have a ton of time over the next couple of days, but I will see if I can take a look if you don't figure it out by then.

**Comment by jrconlin** [comment]
Well, for what it's worth, when I created another 521 key and redid the tokens, everything worked. 

Totally understand your limited time, and I'm in no huge rush. I'll submit the PR (with the modified test) for now and I'll keep poking to figure out what the original problem was. It should be enough to move us forward as well. 

Again, sorry for any hassle, thank you for the library and hope you have a great holiday season. We can pick this up after the new year if that works better for you.

**Comment by mpdavis** [comment]
No worries.  I always appreciate the input.  

Don't feel like you have to wait through the holidays to submit a PR. The earlier I can get my eyes on it, the better.  Also, I usually end up with pockets of time over the holidays that I can use to look at it.

**Comment by mpdavis** [comment]
Agreed.
