### ISSUE TITLE
Python 3.5 support - Encoding errors - JWK

### ISSUE THREAD

**Issue by lchabert** [mpdavis/python-jose#40]
Hi,

I'm working with your lib and Auth0 authentication provider, but when i try to decode my encoded sig, i have a TypeError raised.

Following python code
```python

keys = r.json()['keys']
key = jwk.construct(keys[0])

message, encoded_sig = jwt_value.rsplit('.', 1)
decoded_sig = base64url_decode(encoded_sig)
d = key.verify(message, decoded_sig)
```

and my error is: 
```
  File "/home/lchabert/Documents/Developement/python/voxitrunk-env/lib/python3.5/site-packages/jose/utils.py", line 39, in base64url_decode
    input += b'=' * (4 - rem)
TypeError: Can't convert 'bytes' object to str implicitly
```

I have try to intercept this error on utils.py, and encode the input string. It works, but other encoding errors are raised on 'verify' function too.

Do you know any incompatibility with hashing modules and python 3.5 ?

Thanks,
Regards.

**Comment by mpdavis** [comment]
I don't test against Python 3.5.  The last time I looked into it, getting a Python 3.5 environment setup on Travis CI was a bit of a pain. 

Do you see the same error if you use the jwt api directly?

```python
key = r.json()['keys'][0]
claims = jwt.decode(jwt_value, key, algorithms=['HS256-OR-WHATEVER'])
```

**Comment by lchabert** [comment]
Indeed, it works with this code:

```python
 try:
    payload = jwt.decode(jwt_value, keys, 
                                      algorithms=['RS256'],
                                      audience=settings.AUTH0['AUDIENCE'],
                                      issuer=settings.AUTH0['ISSUER'] )
except jwt.JWTError:
    msg = _('Token not valid.')
    raise exceptions.AuthenticationFailed(msg)
```

I dont understand why other function does not work. They dont call the same functions ?

**Comment by mpdavis** [comment]
Your `jwt_value` appears to be a bytes object.  You should just need to convert it to a str.

Try this: 

```python
keys = r.json()['keys']
key = jwk.construct(keys[0])

jwt_value.encode('utf-8')
message, encoded_sig = jwt_value.rsplit('.', 1)
decoded_sig = base64url_decode(encoded_sig)
```

**Comment by mpdavis** [comment]
@lchabert I am going to close this, assuming that has solved your issue. 

If it has not, feel free to re-open and I can help you out.

**Comment by gdw2** [comment]
I think it's worth re-opening this issue.  At the least, the [documentation](https://python-jose.readthedocs.io/en/latest/jwk/index.html) seems to be out of line with the code.  Docs clearly show `base64url_decode` taking a string whereas it will only take byte arrays. (At least in Python 3).
