### ISSUE TITLE
Various issues in jwt.decode / jws._get_keys

### ISSUE THREAD

**Issue by codertao** [mpdavis/python-jose#45]
I've had a couple issues (figuring out how to use jwt.decode) which stem from the jws._get_keys implementation.

1. key argument must be iterable- raises exception otherwise
2. string key argument must not contain 'keys' (ie if a PEM base64 segment or HS secret segment contains keys, it'll break)
3. key can't be the result of calling jwk.construct (usability issue)
4. attempting json.loads on anything not a string seems weird

**Comment by mpdavis** [comment]
The first three are certainly some cases I have missed due to incorrect assumptions.  I will increase the test coverage for that function and get some fixes in.

Regarding number four, [EAFP](https://docs.python.org/3/glossary.html#term-eafp) is a common practice in Python.

**Comment by jlujan-na** [comment]
> Regarding number four, EAFP is a common practice in Python.

There is an issue when the `key` argument to verify is raw bytes which should be allowed. The `_get_keys` allows only string scalers because of the try: json.loads...except:pass block. Should be...

```
def _get_keys(key):

    try:
        key = json.loads(key)
    except Exception:
        return (key,)
```


example:
```
>>> from jose import jwt
>>> import secrets
>>> secret = secrets.token_bytes(32)
>>> token = jwt.encode({'key': 'value'}, secret)
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJrZXkiOiJ2YWx1ZSJ9.7iPqgH2zMnvqIeO7ccG8KhU5O4AwBm5x1aSUfCtQYGw
>>> jwt.decode(token, secret)
{'key': 'value'}
```

**Comment by alexsavio** [comment]
Another related issue in `.decode` is that the docstring indicating the type for `key` is wrong.
According to `jose.jws._get_key` it could be many other things.

**Comment by takeshixx** [comment]
`_get_keys` also fails for secrets that just contain integers:

```
In [11]: jwt.decode(data, "123456")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-35414fdba59b> in <module>()
----> 1 jwt.decode(data, "123456")

/usr/lib/python3.7/site-packages/jose/jwt.py in decode(token, key, algorithms, options, audience, issuer, subject, access_token)
    133 
    134     try:
--> 135         payload = jws.verify(token, key, algorithms, verify=verify_signature)
    136     except JWSError as e:
    137         raise JWTError(e)

/usr/lib/python3.7/site-packages/jose/jws.py in verify(token, key, algorithms, verify)
     75 
     76     if verify:
---> 77         _verify_signature(signing_input, header, signature, key, algorithms)
     78 
     79     return payload

/usr/lib/python3.7/site-packages/jose/jws.py in _verify_signature(signing_input, header, signature, key, algorithms)
    260         raise JWSError('The specified alg value is not allowed')
    261 
--> 262     keys = _get_keys(key)
    263     try:
    264         if not _sig_matches_keys(keys, signing_input, signature, alg):

/usr/lib/python3.7/site-packages/jose/jws.py in _get_keys(key)
    227 
    228     # JWK Set per RFC 7517
--> 229     if 'keys' in key:
    230         return key['keys']
    231 

TypeError: argument of type 'int' is not iterable
```

**Comment by Sabotaz** [comment]
Hello,

I encoutered problems verifying tokens when key is a string representing an integer (ie: secret = "978917979").

from the code :
```
def _get_keys(key):

    try:
        key = json.loads(key)
    except Exception:
        pass
 ```
The problem is "1234" is a correct json, so the json decoding return an integer, so the key is changed.

`json.loads("1234") == 1234`

**Comment by MatTerra** [comment]
I had the same issue. Will open a PR with a possible solution

**Comment by blag** [comment]
Number 1, 2, and 4 are now fixed, but I believe number 3 is still an issue.

**Comment by blag** [comment]
Fixed number 3 - will try to get a release up on PyPI tonight or later this week.

**Comment by MatTerra** [comment]
Do you have an idea of when you're uploading the new version to PyPI? @blag

**Comment by blag** [comment]
Sorry for the lack of an update. I would like to get #189 merged in for the next release, to finally squash the `str` versus `bytes` issues on Python 3.

I have gotten a bit busy since then, and I'm not going to have a lot of free time to devote to this for about another two weeks.

So to answer your question: at least another two weeks.

If you find the time to lend a hand, please figure out why I'm getting those errors and submit a PR to my `blag:fix-jws-verify` branch.

**Comment by blag** [comment]
Also, @mpdavis - do I need any credentials to upload documentation to Read The Docs?

**Comment by mpdavis** [comment]
@blag I manually built the current docs, and those appear to be serving now. 

I also setup two things in readthedocs. The first was to auto-build and activate a new version any time a tag is cut so we shouldn't need to do that manually in the future. The second was to build on PRs to verify that any changes we make to the docs themselves build correctly.

I'm open to adding you to the project in readthedocs, I just need your username there (not necessarily your github username)

**Comment by blag** [comment]
I didn't realize I needed to be added to that project as well when I first took over maintenance.

I'm `blag` on RTD as well. Thanks for adding me and adding that integration!

**Comment by mpdavis** [comment]
@blag Added.

**Comment by MatTerra** [comment]
> Sorry for the lack of an update. I would like to get #189 merged in for the next release, to finally squash the `str` versus `bytes` issues on Python 3.
> 
> I have gotten a bit busy since then, and I'm not going to have a lot of free time to devote to this for about another two weeks.
> 
> So to answer your question: at least another two weeks.
> 
> If you find the time to lend a hand, please figure out why I'm getting those errors and submit a PR to my `blag:fix-jws-verify` branch.

will take a look

**Comment by MatTerra** [comment]
Update: Opened a PR to solve the missing bugs I could find based on the issues cited on #189. If there's anything else, please let me know.
