### ISSUE TITLE
Wheel please

### ISSUE THREAD

**Issue by peterbe** [mpdavis/python-jose#55]
`python-jose` only exists in pypi as a tarball. [1.3.2 at the time of writing](https://pypi.python.org/pypi/python-jose/1.3.2)
Can we please have this as a wheel too on PyPI?

**Comment by mpdavis** [comment]
I can look into pushing one up.

**Comment by mpdavis** [comment]
I pushed a wheel for 1.3.2 and will add that to releases going forward.

Admittedly, I don't have any experience distributing wheels.  If something isn't correct, re-open this issue and I can get it taken care of.

Thanks for reaching out.

**Comment by peterbe** [comment]
Thanks! I'll try it. 
One problem seems to be that you added a wheel to an existing version. Now my requirements.txt [broke](https://circleci.com/gh/mozilla-services/tecken/350?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) because I had only prepared as a sha for the tarball.
