### ISSUE TITLE
key.py and test.py unused?

### ISSUE THREAD

**Issue by crgk** [mpdavis/python-jose#6]
Quick look, don't think these files are used. Might be used in local testing, but might not need to be committed.

**Comment by crgk** [comment]
0.5.0 looks good though :+1:

**Comment by mpdavis** [comment]
They are currently unused, but are going to be moved into testing.  I'll pull them out for now.

**Comment by mpdavis** [comment]
Fixed in https://github.com/mpdavis/python-jose/releases/tag/v0.5.1
