### ISSUE TITLE
jws.verify type error

### ISSUE THREAD

**Issue by mattsuid** [mpdavis/python-jose#72]
When passing a jwt and key to jws.verify I am getting a type error stating that a bytes like object is required. I can verify the jwt with the key successfully on jwt.io, and am passing byte strings as my arguments.

This:

```
print(type(jwt))
print(type(key))

jws.verify(jwt, key, algorithms=['HS256'])
```

Results in this:

```
<class 'bytes'>
<class 'bytes'>
TypeError, a bytes-like object is required, not 'str'

```

**Comment by blag** [comment]
Might be fixed in #139.
