### ISSUE TITLE
base64url_decode TypeError: must be str, not bytes

### ISSUE THREAD

**Issue by rvernica** [mpdavis/python-jose#74]
Example copied from [docs](http://python-jose.readthedocs.io/en/latest/jwk/index.html):
```python
>>> from jose.utils import base64url_decode
>>> token = "eyJhbGciOiJIUzI1NiIsImtpZCI6IjAxOGMwYWU1LTRkOWItNDcxYi1iZmQ2LWVlZjMxNGJjNzAzNyJ9.SXTigJlzIGEgZGFuZ2Vyb3VzIGJ1c2luZXNzLCBGcm9kbywgZ29pbmcgb3V0IHlvdXIgZG9vci4gWW91IHN0ZXAgb250byB0aGUgcm9hZCwgYW5kIGlmIHlvdSBkb24ndCBrZWVwIHlvdXIgZmVldCwgdGhlcmXigJlzIG5vIGtub3dpbmcgd2hlcmUgeW91IG1pZ2h0IGJlIHN3ZXB0IG9mZiB0by4.s0h6KThzkfBBBkLspW1h84VsJZFTsPPqMDA7g1Md7p0"
>>> message, encoded_sig = token.rsplit('.', 1)
>>> decoded_sig = base64url_decode(encoded_sig)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vernica/.local/lib/python3.6/site-packages/jose/utils.py", line 88, in base64url_decode
    input += b'=' * (4 - rem)
TypeError: must be str, not bytes
```

Environment:
   * Python `3.6.2`
   * jose `1.4.0`

**Comment by flyingbanana1024102** [comment]
In python 3, you have to encode your input to bytes first. Try
`base64url_decode(encoded_sig.encode('utf-8')`

**Comment by karlmutch** [comment]
The append operation within the base64 decode functions is appending bytes not strings resulting in byte arrays being sent to the python base64 functions and failing.

using the encode function on the input strings for padding does not help the root issue.

An example can be seen here:

https://github.com/mpdavis/python-jose/blob/e31416ae2e3c473e551698dcde80bb1977da90bd/jose/utils.py#L88

**Comment by karlmutch** [comment]
> In python 3, you have to encode your input to bytes first, because implicit conversion between str and byte is no longer possible. Try:
> `base64url_decode(encoded_sig.encode('utf-8'))`

The internal functions used for padding will void this fix.  See comment below.
