### ISSUE TITLE
Old version of pycryptodome

### ISSUE THREAD

**Issue by fgblomqvist** [mpdavis/python-jose#78]
How come an over 2 years old version of pycryptodome is used when there are releases that are less than a month old?

The reason why I discovered this is because this pycryptodome does not work on Heroku:
```
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/Crypto/Hash/BLAKE2s.py", line 63, in <module>

remote:     from Crypto.Random import get_random_bytes

remote: ImportError: cannot import name 'get_random_bytes'
```
Not sure if a newer version would fix it but I would assume so.

**Comment by mpdavis** [comment]
I bumped the pycrpytodome to <4.0.0, released in https://github.com/mpdavis/python-jose/releases/tag/2.0.1

**Comment by fgblomqvist** [comment]
Sorry but there seems to be a redundant field causing trouble:
https://github.com/mpdavis/python-jose/blob/master/setup.py#L59
When I run `python setup.py test` it insists on using the old version still since it is specified.

**Comment by mpdavis** [comment]
Well don't just look like a fool?

This should be updated, and I actually tested it this time.

```
~ ❯❯❯ virtualenv ~/.envs/test
New python executable in /Users/michael/.envs/test/bin/python2.7
Also creating executable in /Users/michael/.envs/test/bin/python
Installing setuptools, pip, wheel...done.
~ ❯❯❯ source ~/.envs/test/bin/activate
(test)~ ❯❯❯ pip install python-jose
Collecting python-jose
  Using cached python_jose-2.0.2-py2.py3-none-any.whl
Collecting future<1.0 (from python-jose)
Collecting pycryptodome<4.0.0,>=3.3.1 (from python-jose)
Collecting ecdsa<1.0 (from python-jose)
Collecting six<2.0 (from python-jose)
Installing collected packages: future, pycryptodome, ecdsa, six, python-jose
Successfully installed ecdsa-0.13 future-0.16.0 pycryptodome-3.4.7 python-jose-2.0.2 six-1.11.0
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(test)~ ❯❯❯
```

**Comment by fgblomqvist** [comment]
No worries, now it runs perfectly fine! Thanks for the quick updates.
