### ISSUE TITLE
Use OrderedDict for headers in jwt.decode and jws._encode_header

### ISSUE THREAD

**Issue by Fufutako** [mpdavis/python-jose#80]
Hello,

I would implement the "headless JWT" idea I rode in this article https://dev.to/neilmadden/7-best-practices-for-json-web-tokens the section 4 "Consider using "headless" JWTs" .

But the fact python-jose build the headers from dict make this impossible. Indeed, keys don't have an order in a classic dict. Could you consider to use OrderedDict instead, in jws.py l.131 and jwt.py l.114 ?

If this idea interests you, I could make a pull request.

Best,

**Comment by zejn** [comment]
If I understand you correctly, the keys need need to be predictable for this to work. Would adding the `sort_keys=True` parameter to `json.dumps` be enough?

**Comment by Fufutako** [comment]
yes why not ... I do that with an OrderedDict but sort_key in the dumps works too
