### ISSUE TITLE
Include release notes

### ISSUE THREAD

**Issue by RacingTadpole** [mpdavis/python-jose#99]
Is there a list of what's changed between releases of python-jose? 

I'm having trouble deciding when a new version of python-jose is crucial – eg. because it includes security patches or fixes a bug that could affect my usage – vs when it is just a nice-to-have. Unfortunately redeploying is not always costless.

A change log / release notes would really help with this - or if you already have one, a link to it in the read-me or docs.

Thanks!

**Comment by blag** [comment]
Closed by #132.
